descriptor_extension: yml
package:
  description: ETSI Plugtest ITALTEL
  maintainer: Felipe Vicens, ATOS, felipe.vicens@atos.net
  name: "etsi-italtel"
  vendor: "italtel"
  version: "0.5"
version: '0.5'
